[project]
name = "uv-monorepo"
version = "0.1.0"
description = "UV Monorepo, top-level project for development environment configuration"
authors = [
  {name = "Antoine Robert", email = "antoine.al.robert@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
